version: '3.9'
services:
  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/creator-credentials-prod
    build:
      context: .
    environment:
      APP_PORT: 3100
    volumes:
      - ./:/code
    ports:
      - '3100:3100'
    networks:
      - creator_credentials_prod

networks:
  creator_credentials_prod:
    driver: bridge
