version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # DATABASE_HOSTNAME: 'postgres'
      APP_PORT: 3200
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
      - '3200:3200'
    networks:
      - creator_credentials_dev
  
networks:
  creator_credentials_dev:
    driver: bridge
